site_name: DSDL中文文档

#高亮配置
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
  - pymdownx.details

#提示框配置
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

#主页导航
nav:
  - 语言特性: overview.md
  - 语言定义: 
    - 快速入门: lang/get_started.md
    - 基本数据类型: lang/basic_types.md
    - 非结构化对象类: lang/unstructured_objs.md
    - 结构类: lang/structs.md
    - 链接库: lang/libraries.md
  - 实例演示: 
    - 计算机视觉: examples/cv.md
  - 安装部署: install.md
  - 任务模板: 
    - 计算机视觉: 
      - 图像分类: template/cv/cv_classification.md
      - 目标检测: template/cv/cv_detection.md
    - 自然语言处理: template/nlp/nlp.md
  - 使用教程: tutorial.md

plugins:
  - search:
      lang: 
        - en
        - zh
  - i18n:
      default_language: en
      languages:
        en: 
          name: English
          build: true
          site_name: DSDL Document
        zh: 
          name: 中文
          build: true
          site_name: DSDL中文文档

      nav_translations:
        en:
          语言特性: Overview
          语言定义: Language
          快速入门: Get Started
          基本数据类型: Basic Types
          非结构化对象类: Unstructured Object Classes
          结构类: Struct Classes
          链接库: Libraries
          实例演示: Example
          计算机视觉: Computer Vision
          安装部署: Install
          使用教程: Tutorial
          任务模板: Task Template
          自然语言处理: Natural Language Processing
          图像分类: Image Classification
          目标检测: Object Detection


