site_name: DSDL中文文档
site_author: OpenDataLab
site_description: >-
  基于新一代AI数据集标注语言DSDL（Data Set Description Language），打通AI数据鸿沟，便捷高效使用数据

#高亮配置
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
  - pymdownx.details

#提示框配置
theme:
  name: material
  # custom_dir: overrides
  custom_dir: !ENV [THEME_DIR, "site"]
  language: zh
  features:
    - navigation.tabs
    # - navigation.instant
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

#主页导航
nav:
  - 主页: index.md
  - 入门指南: 
    - 整体介绍: getting_started/install.md
    - 安装部署: getting_started/install.md
    - 实例演示: 
      - 计算机视觉: 
        - 图像分类: getting_started/Detection.md
        - 目标检测: getting_started/Detection.md
  - 用户教程:
    - 整体介绍: tutorials/overview.md
    - 数据集下载: to_be_filled.md
    - 数据集格式转换:
      - 主流格式转换为DSDL格式: to_be_filled.md
      - DSDL格式转换为主流格式: to_be_filled.md
    - 自定义数据集: to_be_filled.md
    - DSDL数据集使用:
      - 框架DataLoader撰写: to_be_filled.md
      - OpenMMLab训练: to_be_filled.md
      - 其他框架训练: to_be_filled.md
    - 数据集可视化: to_be_filled.md
    - 数据集分析: to_be_filled.md
    - ODL-CLI使用教程: to_be_filled.md
  - DSDL规范文档:
    - 语言特性: dsdl_language/overview.md
    - 语言定义: 
      - 快速入门: dsdl_language/lang/get_started.md
      - 基本数据类型: dsdl_language/lang/basic_types.md
      - 非结构化对象类: dsdl_language/lang/unstructured_objs.md
      - 结构类: dsdl_language/lang/structs.md
      - 类别域: dsdl_language/lang/class_dom.md
      - 数据模块: dsdl_language/lang/data_section.md
      - 链接库: dsdl_language/lang/libraries.md
    - 任务模板: 
      - 计算机视觉: 
        - 图像分类: template/cv/cv_classification.md
        - 目标检测: template/cv/cv_detection.md 
    - 实例演示: 
      - 计算机视觉: dsdl_language/examples/cv.md
  - API接口文档: api_reference/index.md

plugins:
  - search:
      lang: 
        - en
        - zh
  - i18n:
      default_language: zh
      languages:
        en: 
          name: English
          build: true
          site_name: DSDL Document
        zh: 
          name: 中文
          build: true
          site_name: DSDL中文文档

      nav_translations:
        en:
          主页: Home
          语言特性: Overview
          语言定义: Language
          整体介绍: overview
          入门指南: Getting Started
          用户教程: Tutorials
          基本数据类型: Basic Types
          非结构化对象类: Unstructured Object Classes
          结构类: Struct Classes
          类别域: Class Domain
          数据模块: Data Section
          链接库: Libraries
          实例演示: Example
          计算机视觉: Computer Vision
          安装部署: Install
          使用教程: Tutorial
          任务模板: Task Template
          自然语言处理: Natural Language Processing
          图像分类: Image Classification
          目标检测: Object Detection


# extra:
#   alternate:

#     # Switch to English
#     - name: English
#       link: <your-site>/en/
#       lang: en

#     # Switch to German
#     - name: Deutsch
#       link: <your-site>/de/
#       lang: de

#     # Switch to Japanese
#     - name: 日本語
#       link: <your-site>/ja/
#       lang: ja
